### ISSUE TITLE
Latest update looking for locks and lights when not in Alarm.com configuration

### ISSUE THREAD

**Issue by DMBlakeley** [mkormendy/homebridge-node-alarm-dot-com#23]
I do not have lights or locks as part of my alarm.com configuration.  Since the latest update I am getting errors such as continuously in the log:

```
[11/22/2019, 7:00:16 PM] [Security Panel] Error: GET https://www.alarm.com/web/api/devices/locks/? failed: [object Object]
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:482:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 3)
    at async Promise.all (index 0)
```

and

```
[11/22/2019, 7:00:16 PM] [Security Panel] Error: GET https://www.alarm.com/web/api/devices/locks/? failed: [object Object]
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:482:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 3)
    at async Promise.all (index 0)
```

Thoughts?

**Comment by chase9** [comment]
Could you try changing your log level to > 2 and post your log after restarting homebridge? I'm interested in how many lights/locks are reported.

**Comment by DMBlakeley** [comment]
Changed log level to 3 and here is the reported log after restart:

`[11/22/2019, 8:23:33 PM] [Security Panel] UNHANDLED ERROR: Error: GET https://www.alarm.com/web/api/devices/locks/? failed: [object Object]
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:482:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 3)
    at async Promise.all (index 0)
[11/22/2019, 8:24:29 PM] [Security Panel] Error: GET https://www.alarm.com/web/api/devices/locks/? failed: [object Object]
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:482:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 3)
    at async Promise.all (index 0)
[11/22/2019, 8:25:30 PM] [Security Panel] Error: GET https://www.alarm.com/web/api/devices/lights/? failed: [object Object]
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:482:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
`

**Comment by lwpmoon** [comment]
Ohhh, derp… Accounts that don’t have subscriptions that enables automations like lights and locks will run into this issue. The GET request is likely being treated as malformed or otherwise invalid. I’m surprised it’s just throwing the exception without giving a 400 series status (something else is going on there).
Anyway, can reproduce by disabling light and lock control for the ADC account that homebridge uses.

**Comment by mkormendy** [comment]
I'm looking into catching this and failing gracefully if lights and locks are not present or the subscription doesn't have them enabled.

**Comment by chase9** [comment]
What is alarm.com returning for lights and locks if they’re not enabled? I haven’t looked into this much, but since homebridge-alarm-dot-com uses res.locks.forEach, I would think this is a problem in node-alarm-dot-com rather than here.

**Comment by lwpmoon** [comment]
It's a 302 redirect (Object moved) probably back home or to a 403 page. You're right, it is indeed technically not this repo but node-alarm-dot-com.
One possible solution would be to try hitting the lock and light URLs to see what kind of account it is before trying to get partitions. If we get a redirect from a URL, the account doesn't have that automation enabled and then we continue accordingly.

**Comment by chase9** [comment]
I just pushed a change to my fork which simply changes 
`if (status >= 400) throw new Error(body.Message || body || status)`
to 
`if (status >= 400) console.error(body.Message || body || status)`

as it seems to me this is where the error would be happening. Could you test this @DMBlakeley or @lwpmoon ?

Another idea is to make light/lock checking opt-in since it would prevent a lot of failed requests to the Alarm.com API. getCurrentState() could accept booleans for locks and lights, and only check those APIs if the user indicates.

**Comment by DMBlakeley** [comment]
I am going to roll back to version 1.2.0. This release was before the addition of lights and locks. Would rather not be sending non required requests to Alarm.com.

**Comment by DMBlakeley** [comment]
Rolled back to version 1.2.0 but still receive the logged lights and locks errors. Not sure if I need to delete the cachedAccessories to erase history of looking for lights or locks.

**Comment by chase9** [comment]
Doug,

Did you also roll back node-alarm-dot-com?

**Comment by DMBlakeley** [comment]
Thanks, didn't realize the dependency with node-alarm-dot-com. Rolled back to 1.6.2 and errors have now subsided. Would certainly like to see a version where "lights" and "locks" could be enabled or disabled.

**Comment by ludgats** [comment]
forgive me ignorance. I have rolled back to version 1.2.0 - how do I roll back to 1.6.2 for node-alarm-dot-com?

**Comment by DMBlakeley** [comment]
This wasn't all that strait forward but here's what I did.  I went to the node-alarm-dot-com [page](https://github.com/mkormendy/node-alarm-dot-com), then the releases section, and downloaded the 1.6.2 package. After stopping Homebridge I overwrote the existing package in the "node-alarm-dot-com" directory. Finally restarted Homebridge.

**Comment by ludgats** [comment]
Dmblakeley

Sounds a bit over my head unfortunately. I’m running everything on a raspberry pi. Hopefully there will be a fix! I love this plugin!

**Comment by chase9** [comment]
The program which handles installing and managing these packages is called `npm`. You're able to specify a version to install by using the format:
`npm install -g <package name>@<version>`. 

So if you wanted to install the previous version of this project you would do:
`npm install -g homebridge-node-alarm-dot-com@1.2.0`.

This will instruct npm to install version 1.2.0 of this project, and should also handle installing the older version of node-alarm-dot-com. **NOTE:** Since you're specifying a version number, this project will no longer automatically install the latest version when there are updates. You're going to have to remember to check back later!

**Comment by DMBlakeley** [comment]
I tried this as a first step. Found that homebridge-node-alarm-dot-com was rolled back, however, node-alarm-dot-com was still at the most recent version. This is why I did the more manual approach.

**Comment by chase9** [comment]
Unfortunately I can't look at why that's not rolling back right now,
but you should be able to manually install node-alarm-dot-com by
entering it's folder and using a similar command.

1. `cd /usr/local/lib/node_modules/homebridge-node-alarm-dot-com`
2. `npm install node-alarm-dot-com@1.6.2`

Of course, this wouldn't need to happen if I could hurry up and provide
a toggle :)

**Comment by DMBlakeley** [comment]
Thanks, this approach works quite nicely.

**Comment by DMBlakeley** [comment]
After rolling back to 1.6.2 I started getting errors such as:

```
[11/27/2019, 9:57:27 AM] [Security Panel] Error: GET https://www.alarm.com/web/api/devices/partitions/92698788-127 failed: request to https://www.alarm.com/web/api/devices/partitions/92698788-127 failed, reason: read ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:334:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
[11/27/2019, 9:57:42 AM] [Security Panel] Logging into Alarm.com as dougblakeley
[11/27/2019, 10:21:30 AM] [Security Panel] Error: GET https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=92698788-5&ids%5B%5D=92698788-6&ids%5B%5D=92698788-1&ids%5B%5D=92698788-7&ids%5B%5D=92698788-4&ids%5B%5D=92698788-2&ids%5B%5D=92698788-3 failed: request to https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=92698788-5&ids%5B%5D=92698788-6&ids%5B%5D=92698788-1&ids%5B%5D=92698788-7&ids%5B%5D=92698788-4&ids%5B%5D=92698788-2&ids%5B%5D=92698788-3 failed, reason: read ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:334:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
```
 Found by increasing increasing "POLL_TIMEOUT_SECS" from 60 to 90 in homebridge-node-alarm-com/index.js these errors also seem to have stopped.

**Comment by ludgats** [comment]
Chas9 

Your solution worked great for me! thank you!

**Comment by Danimal4326** [comment]
Is the a possibility of adding a config to disable lights/switches etc in a future version?

**Comment by cwhorton** [comment]
Would this issue prevent a new user from adding their security system to HomeKit?  Today I installed this plugin for the first time and I see these errors in the logs but the "Security System" accessory is not being presented in the Home app for me to add.

**Comment by mkormendy** [comment]
@Danimal4326 I've been swamped at work with major projects for end of year for the past 3 weeks. I've been meaning to touch this project on the weekends, but even then, I haven't been able to balance work/life/hobbies as well as I want to.

Ideally this would automatically be detected and gracefully not require them.

@cwhorton, if you scroll up a bit in this issue thread, you can use the previous releases of the homebridge plugin and the node package of the alarm dot com connector.

**Comment by cwhorton** [comment]
@mkormendy, Thank you for your response.  I did see I could roll back, but I wasn't sure if the issue was just erroneous calls and logging versus actually affecting functionality.

**Comment by knuckleheadsmiff** [comment]
I vote also to have a config setting to ignore/disable sending requests to alarm.com, if you can’t easily detect, if we don’t have lights and locks.

**Comment by chase9** [comment]
Hey guys, I'm sorry I've been AFK for a while. I'm trying something new where we rely on how many lights and locks are returned in the initial login, so hopefully this is more graceful then a option in the config. Could someone having issues please checkout the latest from my branch?

**Comment by efloyd** [comment]
I don't have locks or lights, only sensors, but happy to help test in any way that I can to help you get this pushed through.

**Comment by chase9** [comment]
Thanks @efloyd. The code itself is pretty straightforward, but I would like someone affected to test to make sure there's no more unforeseen consequences 😅

**Comment by mkormendy** [comment]
@efloyd @chase9 @knuckleheadsmiff @cwhorton @Danimal4326 et al,

Well it's finally the new year, and I've managed to finish the 2019 last quarter project at my current job, and have some downtime now to create a couple options to ignore devices for this if the user doesn't have them and also provide some logging feedback to suggest that the user doesn't have specific accessories on their account.

Look for an update over the next couple days/week.

PS. I'm also looking into the 2FA issue as well and hope to provide a workaround for that too.

**Comment by mkormendy** [comment]
@efloyd @chase9 @knuckleheadsmiff @cwhorton @Danimal4326 I just pushed an update that basically skips over empty reported devices. I also managed to update the package json first and also updated the node-alarm-dot-com module so everything should update the first time. We could likely refactor this at a later time, but this was the most straightforward way of doing this - as we add other accessories, we can see how they report and come up with an overall accessory provision class.

**Comment by Danimal4326** [comment]
Fantastic!  No more errors here.

Seeing the following in the logs at startup:
[1/13/2020, 10:18:47 AM] [Security System] Received no lights from Alarm.com. If you are expecting
            lights in your Alarm.com setup, you may need to check that your 
            provider has assigned lights in your Alarm.com account
[1/13/2020, 10:18:47 AM] [Security System] Received no locks from Alarm.com. If you are expecting
            locks in your Alarm.com setup, you may need to check that your 
            provider has assigned locks in your Alarm.com account

**Comment by mkormendy** [comment]
@Danimal4326 great! You should only see those messages when you boot up homebridge, or to turn them off you can change the log level to 2 or 1.

**Comment by DMBlakeley** [comment]
After the latest update I am still getting errors such as:

```
[1/14/2020, 10:31:09 AM] [Security Panel] Error: GET https://www.alarm.com/web/api/devices/partitions/92698788-127 failed: request to https://www.alarm.com/web/api/devices/partitions/92698788-127 failed, reason: read ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:495:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```
92698788-127 is the security panel itself. I also did not observe the startup messages as reported by @Danimal4326 as I do not have lights or locks.

Any suggestions appreciated.

**Comment by Danimal4326** [comment]
@DMBlakeley I do not have lights or locks either.  Hence I was getting errors previously.  
The new logs show the change is working, and its turning off the lights/locks feature.

I have not seen the error you're seeing. I can check my logs and report back

**Comment by knuckleheadsmiff** [comment]
I too see what DMBlakeley sees. I believe (not 100% positive) I saw this before the latest update but just ignored it because of all the other errors ta were logged.

**Comment by mkormendy** [comment]
> After the latest update I am still getting errors such as:
> 
> ```
> [1/14/2020, 10:31:09 AM] [Security Panel] Error: GET https://www.alarm.com/web/api/devices/partitions/92698788-127 failed: request to https://www.alarm.com/web/api/devices/partitions/92698788-127 failed, reason: read ETIMEDOUT
>     at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:495:13
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:94:5)
>     at async Promise.all (index 0)
>     at async Promise.all (index 0)
>     at async Promise.all (index 0)
> ```
> 
> 92698788-127 is the security panel itself. I also did not observe the startup messages as reported by @Danimal4326 as I do not have lights or locks.
> 
> Any suggestions appreciated.

Is this the only error now?

As far as @Danimal4326's "startup messages", you won't see those if your security panel can't successfully log in.

Have you tried deleting the `cachedAccessories` file?

**Comment by DMBlakeley** [comment]
I have had other errors such as the following. Will try deleting `cachedAccessores` file.

```
[1/14/2020, 5:14:43 AM] [Security Panel] Error: POST https://www.alarm.com/pda/(S(kolmkixd4cs2nqcvq30ksb3k))/Default.aspx failed: GET https://www.alarm.com/web/Default.aspx?fromRimDotNet=true&loginAs=1&loginAsKey=9850AEE078A9EA29702008C5DB47F61474A4347C2DD948E943 failed:
                              GET https://www.alarm.com/web/Default.aspx?fromRimDotNet=true&loginAs=1&loginAsKey=9850AEE078A9EA29702008C5DB47F61474A4347C2DD948E943 failed: request to https://www.alarm.com/web/Default.aspx?fromRimDotNet=true&loginAs=1&loginAsKey=9850AEE078A9EA29702008C5DB47F61474A4347C2DD948E943 failed, reason: read ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:156:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[1/14/2020, 5:15:00 AM] [Security Panel] Logging into Alarm.com as dougblakeley
[1/14/2020, 5:15:02 AM] [Security Panel] Logged into Alarm.com as dougblakeley
[1/14/2020, 5:26:01 AM] [Security Panel] Logging into Alarm.com as dougblakeley
[1/14/2020, 5:26:03 AM] [Security Panel] Logged into Alarm.com as dougblakeley
[1/14/2020, 5:33:44 AM] [Security Panel] Error: GET https://www.alarm.com/web/api/systems/systems/2736084 failed: request to https://www.alarm.com/web/api/systems/systems/2736084 failed, reason: read ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:495:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Promise.all (index 0)
```

**Comment by Danimal4326** [comment]
Update: No such errors seen here.

**Comment by DMBlakeley** [comment]
Deleted `cachedAccessories` file and no errors in 4+ hours. Really need to wait 24 hours before declaring success. Will provide update tomorrow.

**Comment by mkormendy** [comment]
It would show you errors immediately. This is resolved.

**Comment by DMBlakeley** [comment]
No errors overnight so I agree this is resolved/closed.

**Comment by DMBlakeley** [comment]
After update to 1.4.1 and restart received the following error pretty quickly after reboot:

```
[1/15/2020, 8:52:02 AM] [Security Panel] Error: GET https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=92698788-5&ids%5B%5D=92698788-6&ids%5B%5D=92698788-1&ids%5B%5D=92698788-7&ids%5B%5D=92698788-4&ids%5B%5D=92698788-2&ids%5B%5D=92698788-3 failed: request to https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=92698788-5&ids%5B%5D=92698788-6&ids%5B%5D=92698788-1&ids%5B%5D=92698788-7&ids%5B%5D=92698788-4&ids%5B%5D=92698788-2&ids%5B%5D=92698788-3 failed, reason: read ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:475:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
```

**Comment by mkormendy** [comment]
> After update to 1.4.1 and restart received the following error pretty quickly after reboot. Have deleted accessoriesCache and restarted.
> 
> ```
> [1/15/2020, 8:52:02 AM] [Security Panel] Error: GET https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=92698788-5&ids%5B%5D=92698788-6&ids%5B%5D=92698788-1&ids%5B%5D=92698788-7&ids%5B%5D=92698788-4&ids%5B%5D=92698788-2&ids%5B%5D=92698788-3 failed: request to https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=92698788-5&ids%5B%5D=92698788-6&ids%5B%5D=92698788-1&ids%5B%5D=92698788-7&ids%5B%5D=92698788-4&ids%5B%5D=92698788-2&ids%5B%5D=92698788-3 failed, reason: read ETIMEDOUT
>     at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:475:13
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:94:5)
>     at async Promise.all (index 1)
>     at async Promise.all (index 0)
> ```

Hrmm .. I can't reproduce. Anyone else having this exact sort of response?

**Comment by knuckleheadsmiff** [comment]
> > After update to 1.4.1 and restart received the following error pretty quickly after reboot. Have deleted accessoriesCache and restarted.
> > ```
> > [1/15/2020, 8:52:02 AM] [Security Panel] Error: GET https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=92698788-5&ids%5B%5D=92698788-6&ids%5B%5D=92698788-1&ids%5B%5D=92698788-7&ids%5B%5D=92698788-4&ids%5B%5D=92698788-2&ids%5B%5D=92698788-3 failed: request to https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=92698788-5&ids%5B%5D=92698788-6&ids%5B%5D=92698788-1&ids%5B%5D=92698788-7&ids%5B%5D=92698788-4&ids%5B%5D=92698788-2&ids%5B%5D=92698788-3 failed, reason: read ETIMEDOUT
> >     at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:475:13
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (internal/process/task_queues.js:94:5)
> >     at async Promise.all (index 1)
> >     at async Promise.all (index 0)
> > ```
> 
> Hrmm .. I can't reproduce. Anyone else having this **EXACT** sort of response?

I see the exact same thing often when starting up.

**Comment by mkormendy** [comment]
Can you guys see what version of node-alarm-dot-com is being used?

**Comment by DMBlakeley** [comment]
node-alarm-dot-com is v1.7.5
homebridge-node-alarm-dot-com is v1.4.1

**Comment by knuckleheadsmiff** [comment]
`pi@raspberrypi:~ $ sudo npm view homebridge-node-alarm-dot-com version
1.4.1
pi@raspberrypi:~ $ sudo npm view node-alarm-dot-com  version
1.7.5
`

and my log: (always see this at startup. I reboot my raspberry pi daily.)

`[1/15/2020, 5:00:21 AM] Homebridge is running on port 51826.
[1/15/2020, 5:00:21 AM] [Security System] UNHANDLED ERROR: Error: GET https://www.alarm.com/pda/Default.aspx failed: request to https://www.alarm.com/pda/Default.aspx failed, reason: getaddrinfo ENOTFOUND www.alarm.com
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:495:13
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[1/15/2020, 5:00:21 AM] [HubName] Error - Error retrieving info from hub : Error: connect ENETUNREACH 192.168.87.20:8088 - Local (0.0.0.0:0)-(1)
[1/15/2020, 5:00:25 AM] [Config] Homebridge Config UI X v4.7.0 is listening on :: port 8080`

But things then see to work fine. Bit early I may see this sometimes later in the day:
`[1/15/2020, 10:09:55 AM] [Security System] Logging into Alarm.com as russell.sonnenschein@gmail.com
[1/15/2020, 10:09:57 AM] [Security System] Logged into Alarm.com as russell.sonnenschein@gmail.com
[1/15/2020, 10:14:05 AM] [Security System] Error: GET https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=95038009-4&ids%5B%5D=95038009-5&ids%5B%5D=95038009-10&ids%5B%5D=95038009-9&ids%5B%5D=95038009-15&ids%5B%5D=95038009-2&ids%5B%5D=95038009-3&ids%5B%5D=95038009-12&ids%5B%5D=95038009-14&ids%5B%5D=95038009-13&ids%5B%5D=95038009-1&ids%5B%5D=95038009-7&ids%5B%5D=95038009-6&ids%5B%5D=95038009-8&ids%5B%5D=95038009-71&ids%5B%5D=95038009-11 failed: request to https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=95038009-4&ids%5B%5D=95038009-5&ids%5B%5D=95038009-10&ids%5B%5D=95038009-9&ids%5B%5D=95038009-15&ids%5B%5D=95038009-2&ids%5B%5D=95038009-3&ids%5B%5D=95038009-12&ids%5B%5D=95038009-14&ids%5B%5D=95038009-13&ids%5B%5D=95038009-1&ids%5B%5D=95038009-7&ids%5B%5D=95038009-6&ids%5B%5D=95038009-8&ids%5B%5D=95038009-71&ids%5B%5D=95038009-11 failed, reason: connect ETIMEDOUT 192.155.71.71:443
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:495:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
[1/15/2020, 10:20:55 AM] [Security System] Logging into Alarm.com as russell.sonnenschein@gmail.com`

**Comment by knuckleheadsmiff** [comment]
I should add, that even though I see this in the logs things seem to then work. But the first error I listed seems to happen all the time before a successful login.

**Comment by mkormendy** [comment]
> and my log: (always see this at startup. I reboot my raspberry pi daily.)
> 
> ```
> [1/15/2020, 5:00:21 AM] Homebridge is running on port 51826.
> [1/15/2020, 5:00:21 AM] [Security System] UNHANDLED ERROR: Error: GET https://www.alarm.com/pda/Default.aspx failed: request to https://www.alarm.com/pda/Default.aspx failed, reason: getaddrinfo ENOTFOUND www.alarm.com
>     at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:495:13
>     at processTicksAndRejections (internal/process/task_queues.js:94:5)
> [1/15/2020, 5:00:21 AM] [HubName] Error - Error retrieving info from hub : Error: connect ENETUNREACH 192.168.87.20:8088 - Local (0.0.0.0:0)-(1)
> [1/15/2020, 5:00:25 AM] [Config] Homebridge Config UI X v4.7.0 is listening on :: port 8080
> ```
> 
> But things then see to work fine.
> 

@knuckleheadsmiff that seems like a LAN DNS resolving issue of some sorts because it is also happening with your other homebridge plugin [HubName] `Error retrieving info from hub : Error: connect ENETUNREACH 192.168.87.20:8088`.

Both plugins, at first, can't seem to resolve the URL/IPs for their respective resources.

I'm not sure what your networking setup is, but this could be due to the way your networking is configured.

**Comment by mkormendy** [comment]
@knuckleheadsmiff your command for finding the version of your installed versions of the homebridge plugins is incorrect. You're getting the package version on the public npm _registry_, not the locally installed version.

Please use the following command instead, which should list both parts of this project:
```
sudo npm list node-alarm-dot-com
```

**Comment by knuckleheadsmiff** [comment]
> @knuckleheadsmiff your command for finding the version of your installed versions of the homebridge Alarm.com plugins is incorrect. You're getting the package version on the public npm _registry_, not the locally installed version.
> 
> Please use the following command instead, which should list both parts of this plugin:
> 
> ```
> sudo npm list node-alarm-dot-com
> ```

Yes. I think it is a raspberian network of HomeBridge network initialization error. I’m not worried but just thought I’d report it. Since it happens every system reboot I could narrow it down to the OS or HomeBridge startup. I could also write something to tickle the network on reboot before starting HomeBridge I suspose.

**Comment by mkormendy** [comment]
Yes. I think it is a raspberian network of HomeBridge network initialization error. I’m not worried but just thought I’d report it. Since it happens every system reboot I could narrow it down to the OS or HomeBridge startup. I could also write something to tickle the network on reboot before starting HomeBridge I suspose.

@knuckleheadsmiff cool, do what you want with that. Back to the topic at hand, did you see the command I talked about, for getting the correct versions of your locally installed Alarm.com plugin?

**Comment by knuckleheadsmiff** [comment]
> > Yes. I think it is a raspberian network of HomeBridge network initialization error. I’m not worried but just thought I’d report it. Since it happens every system reboot I could narrow it down to the OS or HomeBridge startup. I could also write something to tickle the network on reboot before starting HomeBridge I suspose.
> 
> @knuckleheadsmiff cool, do what you want with that. Back to the topic at hand, did you see the command I talked about, for getting the correct versions of your locally installed Alarm.com plugin?


I did but I won’t be home until late this afternoon.

**Comment by knuckleheadsmiff** [comment]
> > Yes. I think it is a raspberian network of HomeBridge network initialization error. I’m not worried but just thought I’d report it. Since it happens every system reboot I could narrow it down to the OS or HomeBridge startup. I could also write something to tickle the network on reboot before starting HomeBridge I suspose.
> 
> @knuckleheadsmiff cool, do what you want with that. Back to the topic at hand, did you see the command I talked about, for getting the correct versions of your locally installed Alarm.com plugin?

Here you go.

`pi@raspberrypi:~ $ sudo npm list node-alarm-dot-com -g
/usr/lib
└─┬ homebridge-node-alarm-dot-com@1.4.0
  └── node-alarm-dot-com@1.7.1`

**Comment by mkormendy** [comment]
> Here you go.
pi@raspberrypi:~ $ sudo npm list node-alarm-dot-com -g
/usr/lib
└─┬ homebridge-node-alarm-dot-com@1.4.0
  └── node-alarm-dot-com@1.7.1

Well there we have it. You’re not not in the latest versions with the fix.

**Comment by knuckleheadsmiff** [comment]
Odd. I reupdated and now it is correct. I'll reboot and look at my logs.

```
pi@raspberrypi:~ $ sudo npm list node-alarm-dot-com -g
/usr/lib
└─┬ homebridge-node-alarm-dot-com@1.4.1
  └── node-alarm-dot-com@1.7.5 

```

**Comment by knuckleheadsmiff** [comment]
So far things look good. Actually this time on reboot I see no log errors (even the ones that showed earlier?)

```
Started Homebridge.
[1/16/2020, 3:30:04 PM] Loaded config.json with 1 accessories and 4 platforms.
[1/16/2020, 3:30:04 PM] ---
[1/16/2020, 3:30:04 PM] Loaded plugin: homebridge-config-ui-x
[1/16/2020, 3:30:04 PM] Registering platform 'homebridge-config-ui-x.config'
[1/16/2020, 3:30:04 PM] ---
[1/16/2020, 3:30:05 PM] Loaded plugin: homebridge-garagedoor-ryobi
[1/16/2020, 3:30:05 PM] Registering accessory 'homebridge-garagedoor-ryobi.RyobiGarageCommand'
[1/16/2020, 3:30:05 PM] ---
[1/16/2020, 3:30:09 PM] Loaded plugin: homebridge-harmony
[1/16/2020, 3:30:09 PM] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket'
[1/16/2020, 3:30:09 PM] ---
[1/16/2020, 3:30:09 PM] Loaded plugin: homebridge-node-alarm-dot-com
[1/16/2020, 3:30:09 PM] Registering platform 'homebridge-node-alarm-dot-com.Alarmdotcom'
[1/16/2020, 3:30:09 PM] ---
[1/16/2020, 3:30:10 PM] Loaded plugin: homebridge-weather-plus
[1/16/2020, 3:30:12 PM] Registering platform 'homebridge-weather-plus.WeatherPlus'
[1/16/2020, 3:30:12 PM] ---
[1/16/2020, 3:30:12 PM] Loading 4 platforms...
[1/16/2020, 3:30:12 PM] [Config] Initializing config platform...
[1/16/2020, 3:30:12 PM] [Config] Spawning homebridge-config-ui-x with PID 1016
[1/16/2020, 3:30:12 PM] [Security System] Initializing Alarmdotcom platform...
[1/16/2020, 3:30:12 PM] [WeatherPlus] Initializing WeatherPlus platform...
[1/16/2020, 3:30:12 PM] [WeatherPlus] Adding station with weather service Weather Underground named 'Outside'
[1/16/2020, 3:30:12 PM] [WeatherPlus] Initializing platform accessory 'Outside'...
[1/16/2020, 3:30:12 PM] [HubName] Initializing HarmonyHubWebSocket platform...
[1/16/2020, 3:30:12 PM] [HubName] HarmonyPlatform Init
[1/16/2020, 3:30:12 PM] [HubName] undefined
[1/16/2020, 3:30:12 PM] Loading 1 accessories...
[1/16/2020, 3:30:12 PM] [Garage Door] Initializing RyobiGarageCommand accessory...
[1/16/2020, 3:30:12 PM] [HubName] WARNING - configureAccessory - TV accessory added in your bridge from cache, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: key fob leslie (95038009-12)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Key Fob Russ (95038009-14)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Key Fob spare (95038009-13)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Panel Camera (71) (95038009-71)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Panel (95038009-127)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Back Door (95038009-4)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Back Window (95038009-5)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Bedroom Window (95038009-10)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Dining Room Window (95038009-9)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Family Room Motion Detector (95038009-15)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Front Door (95038009-2)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Garage Door (95038009-3)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: kitchen garage door (95038009-1)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Kitchen Window (95038009-7)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Master Bedroom Window (95038009-6)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Office Window (95038009-8)
[1/16/2020, 3:30:12 PM] [Security System] Loaded from cache: Side garage door (95038009-11)
Setup Payload:
X-HM://0023OVKLBIGA2
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐
    │ 133-44-255 │
    └────────────┘
                       
[1/16/2020, 3:30:12 PM] [Security System] Logging into Alarm.com as russell.sonnenschein@gmail.com
[1/16/2020, 3:30:12 PM] [HubName] DidFinishLaunching
[1/16/2020, 3:30:12 PM] [HubName] INFO - Loading activities...
[1/16/2020, 3:30:12 PM] Homebridge is running on port 51826.
[1/16/2020, 3:30:13 PM] [HubName] (HubName)INFO - configuring Main TV Service
[1/16/2020, 3:30:14 PM] [HubName] (HubName)INFO - Configuring Main Activity Watch Apple TV
[1/16/2020, 3:30:15 PM] [Security System] Logged into Alarm.com as russell.sonnenschein@gmail.com
[1/16/2020, 3:30:15 PM] [Security System] Received 1 partitions(s) from Alarm.com
[1/16/2020, 3:30:15 PM] [Security System] Removing Panel (95038009-127) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding partition Panel (id=95038009-127, uuid=93ef7617-c4ec-4626-b1c2-7beafdc27c47)
[1/16/2020, 3:30:16 PM] [Security System] Updating partition Panel (95038009-127), state=3, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Updating partition Panel (95038009-127), desiredState=3, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Updating partition Panel (95038009-127), statusFault=false, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added partition Panel (95038009-127)
[1/16/2020, 3:30:16 PM] [Security System] Received 16 sensor(s) from Alarm.com
[1/16/2020, 3:30:16 PM] [Security System] Removing Back Door (95038009-4) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding Contact Sensor "Back Door" (id=95038009-4, uuid=cf0f0cab-48a0-49c1-9512-6188fc6ee4ac)
[1/16/2020, 3:30:16 PM] [Security System] Updating sensor Back Door (95038009-4), state=0, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added sensor Back Door (95038009-4)
[1/16/2020, 3:30:16 PM] [Security System] Removing Back Window (95038009-5) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding Contact Sensor "Back Window" (id=95038009-5, uuid=fd4d0fdf-20c3-478f-b6db-cdac0e29a211)
[1/16/2020, 3:30:16 PM] [Security System] Updating sensor Back Window (95038009-5), state=0, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added sensor Back Window (95038009-5)
[1/16/2020, 3:30:16 PM] [Security System] Removing Bedroom Window (95038009-10) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding Contact Sensor "Bedroom Window" (id=95038009-10, uuid=91ee04a1-5dda-4cbd-9f60-a1a80183a1ee)
[1/16/2020, 3:30:16 PM] [Security System] Updating sensor Bedroom Window (95038009-10), state=0, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added sensor Bedroom Window (95038009-10)
[1/16/2020, 3:30:16 PM] [Security System] Removing Dining Room Window (95038009-9) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding Contact Sensor "Dining Room Window" (id=95038009-9, uuid=bff43cc1-f34d-48df-8c78-69c3917842b3)
[1/16/2020, 3:30:16 PM] [Security System] Updating sensor Dining Room Window (95038009-9), state=0, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added sensor Dining Room Window (95038009-9)
[1/16/2020, 3:30:16 PM] [Security System] Removing Family Room Motion Detector (95038009-15) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding Occupancy Sensor "Family Room Motion Detector" (id=95038009-15, uuid=ca452e1b-46b6-401a-a5f4-3c54f1361957)
[1/16/2020, 3:30:16 PM] [Security System] Updating sensor Family Room Motion Detector (95038009-15), state=1, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added sensor Family Room Motion Detector (95038009-15)
[1/16/2020, 3:30:16 PM] [Security System] Removing Front Door (95038009-2) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding Contact Sensor "Front Door" (id=95038009-2, uuid=dd79d724-87ab-4163-9d19-30987fa357c7)
[1/16/2020, 3:30:16 PM] [Security System] Updating sensor Front Door (95038009-2), state=0, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added sensor Front Door (95038009-2)
[1/16/2020, 3:30:16 PM] [Security System] Removing Garage Door (95038009-3) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding Contact Sensor "Garage Door" (id=95038009-3, uuid=abf7f5c5-601e-4e8a-887d-159b68656f7c)
[1/16/2020, 3:30:16 PM] [Security System] Updating sensor Garage Door (95038009-3), state=0, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added sensor Garage Door (95038009-3)
[1/16/2020, 3:30:16 PM] [Security System] Ignored sensor key fob leslie (95038009-12)
[1/16/2020, 3:30:16 PM] [Security System] Ignored sensor Key Fob Russ (95038009-14)
[1/16/2020, 3:30:16 PM] [Security System] Ignored sensor Key Fob spare (95038009-13)
[1/16/2020, 3:30:16 PM] [Security System] Removing kitchen garage door (95038009-1) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding Contact Sensor "kitchen garage door" (id=95038009-1, uuid=e3ce498e-8d28-4564-9f0a-02e57b3858b2)
[1/16/2020, 3:30:16 PM] [Security System] Updating sensor kitchen garage door (95038009-1), state=0, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added sensor kitchen garage door (95038009-1)
[1/16/2020, 3:30:16 PM] [Security System] Removing Kitchen Window (95038009-7) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding Contact Sensor "Kitchen Window" (id=95038009-7, uuid=a3067d6f-b6cc-4d02-bfed-c9044cd6ecc8)
[1/16/2020, 3:30:16 PM] [Security System] Updating sensor Kitchen Window (95038009-7), state=0, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added sensor Kitchen Window (95038009-7)
[1/16/2020, 3:30:16 PM] [Security System] Removing Master Bedroom Window (95038009-6) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding Contact Sensor "Master Bedroom Window" (id=95038009-6, uuid=3319be47-b57c-41ef-9f84-c0b57e065e15)
[1/16/2020, 3:30:16 PM] [Security System] Updating sensor Master Bedroom Window (95038009-6), state=0, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added sensor Master Bedroom Window (95038009-6)
[1/16/2020, 3:30:16 PM] [Security System] Removing Office Window (95038009-8) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding Contact Sensor "Office Window" (id=95038009-8, uuid=67d22e86-01cd-40a5-8d82-a07a2649737b)
[1/16/2020, 3:30:16 PM] [Security System] Updating sensor Office Window (95038009-8), state=0, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added sensor Office Window (95038009-8)
[1/16/2020, 3:30:16 PM] [Security System] Ignored sensor Panel Camera (71) (95038009-71)
[1/16/2020, 3:30:16 PM] [Security System] Removing Side garage door (95038009-11) from HomeBridge.
[1/16/2020, 3:30:16 PM] [Security System] Adding Contact Sensor "Side garage door" (id=95038009-11, uuid=159b71dc-5b6e-4c6a-9d75-50f09187f2a6)
[1/16/2020, 3:30:16 PM] [Security System] Updating sensor Side garage door (95038009-11), state=0, prev=null
[1/16/2020, 3:30:16 PM] [Security System] Added sensor Side garage door (95038009-11)
[1/16/2020, 3:30:17 PM] [Config] Homebridge Config UI X v4.7.0 is listening on :: port 8080
[1/16/2020, 3:31:02 PM] [Garage Door] State of Garage Door is: CLOSED
homebridge : TTY=pts/0 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)

```

**Comment by mkormendy** [comment]
@knuckleheadsmiff thats great news!

@DMBlakeley Can you try the following command in your terminal which should list both parts of this plugin, and report back:
```
sudo npm list node-alarm-dot-com
```

**Comment by DMBlakeley** [comment]
Received the following response on Mac mini with OS X 10.11.6
```
/usr/local/lib
└─┬ homebridge-node-alarm-dot-com@1.4.1
  └── node-alarm-dot-com@1.7.5  extraneous

npm ERR! extraneous: node-alarm-dot-com@1.7.5 /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com
```
Still seeing errors from alarm.com. Saw following twice from last night
```
[1/17/2020, 2:40:06 AM] [Security Panel] Error: GET https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=92698788-5&ids%5B%5D=92698788-6&ids%5B%5D=92698788-1&ids%5B%5D=92698788-7&ids%5B%5D=92698788-4&ids%5B%5D=92698788-2&ids%5B%5D=92698788-3 failed: request to https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=92698788-5&ids%5B%5D=92698788-6&ids%5B%5D=92698788-1&ids%5B%5D=92698788-7&ids%5B%5D=92698788-4&ids%5B%5D=92698788-2&ids%5B%5D=92698788-3 failed, reason: read ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:475:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
```

**Comment by mkormendy** [comment]
@DMBlakeley what version of node are you running? To get that please run this command:
```
sudo node -v
```
Also are you using PM2 or native node for running the Homebridge process?
It looks as though you're using Homebridge right? Not Hoobs?
What does your config look like for this plugin in your Homebridge config (remove usernames/passwords)?

What system are you on as well? Raspberry Pi w/ Linux? Mac? Windows?
What OS version?

Any and all relevant information about your Alarm.com setup would also be helpful.
Such as, do you have 2FA enabled?
What kinds of sensors and/or accessories do you have?

Sorry to ask all of these questions, since I can't reproduce and others are having success, it's hard for me to nail down why you're not getting the same results as others.

**Comment by knuckleheadsmiff** [comment]
I’d suggest running the version commands as -g if it is running global verses local. Could have multiple versions installed.

**Comment by DMBlakeley** [comment]
Not a problem on the questions. Believe I have answer all of them. In response to @knuckleheadsmiff comment I believe that I used -g for install per your instructions but I did a reinstall with `sudo npm install -g homebridge-node-alarm-dot-com@latest`.

`sudo node -v` returns `v12.14.1`

I am running Homebridge (not Hoobs) on a Mac mini OS X 10.11.6

Config file:
 ```
      {
            "platform": "Alarmdotcom",
            "name": "Security Panel",
            "username": "<<redacted>>",
            "password": "<<redacted>>",
            "armingModes": {
                "away": {
                    "noEntryDelay": false,
                    "silentArming": false
                },
                "night": {
                    "noEntryDelay": false,
                    "silentArming": false
                },
                "stay": {
                    "noEntryDelay": false,
                    "silentArming": false
                }
            },
            "logLevel": 3
        },
```
2FA is not enable in Alarm.com account. Have doors, windows and motion sensors. No lights or cameras.

Additional Homebridge devices include: Ring doorbell, Chamberlain garage door, Nest thermostat and Protect smoke detect, older Wemo plugs/switches which cannot be updated to native HomeKit, and Belkin Netcam cameras. Also recently added Config UI X for Homebridge status but alarm-dot-com errors were happening before adding.

The Chamberlain garage door is also throwing ECONNRESET errors but author of that plug-in is aware.

**Comment by mkormendy** [comment]
@DMBlakeley this baffles me. The only thing that stands out is your OS version and the Chamberlain issue, but that shouldn’t matter to much as the plugins should run in separation from each other. The OS being a couple versions behind shouldn’t matter too much either, you’re running the same version of node as me and have a similar Mac Mini setup. I’m running mine on Mojave.

My recommendation would be to downgrade to the previous version, as that appears to have had success, and it has all of the functionality that the current version has, without the code refactoring. The only gain on the latest version is that the code is cleaned up to be more efficient and manageable, it does however use one method (versus multiple separate unique methods) to process all of the calls for all components/accessories - that’s it. I can’t for the life of me see why you’re the only one having this issue while others that have upgraded have not.

I haven’t asked, but have you tried disabling all of the other homebridge plugins and leaving just this one?

**Comment by DMBlakeley** [comment]
@mkormendy thanks for reviewing my setup. This is an older Mac mini and why it is running an older version of OS X. Homebridge is really the only task that is running other than the occasional logins.

Since doing the reinstall of homebridge-alarm-dot-com as noted above I have only received one error:
```
[1/17/2020, 9:02:12 PM] [Security Panel] Error: GET https://www.alarm.com/web/api/systems/systems/2736084 failed: request to https://www.alarm.com/web/api/systems/systems/2736084 failed, reason: read ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:475:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Promise.all (index 0)
```
which seems like a general login error rather than device issues. Will continue to monitor but an occasional error doesn't seem to be a big issue.

Thanks again for your help.

**Comment by mkormendy** [comment]
Hey now,... that looks way better!

ETIMEDOUT errors with this plugin are indicative of network latency problems, but I believe in the earlier posts at the beginning of this thread, you managed to fix it by increasing increasing "POLL_TIMEOUT_SECS" from 60 to 90 in the index.js file.

Instead of editing the plugin itself, there's a config setting that you can pass to the plugin just by adding the following in your homebridge config.json file in the plugin's config section:

```
"pollTimeoutSeconds": 90
```
The default is set to 60, but you mentioned you had success with 90 seconds in your use-case.
Give that a try.

For illustrative purposes, here's an example of how that would look in the plugin's config section:
```
{
    "platform": "Alarmdotcom",
    "name": "Security System",
    "username": "<USERNAME>",
    "password": "<PASSWORD>",
    "pollTimeoutSeconds": 90
}
```

**Comment by DMBlakeley** [comment]
Thanks for the tip on changing "pollTimeoutSeconds". Will update my config.json accordingly.

**Comment by knuckleheadsmiff** [comment]
FYI... 

On Raspberian, I was having some networking DNS lookup errors when rebooting and starting homebridge and then looking for the alarm.com endpoint (and another service had a similar problem.)  If I just restarted the homebridge server with out a reboot I did not have any issues. This prevented re enumerating all my devices and only using the devices i my cache (which was working fine.) 

This was the case even though homebridge was setup to start after networking was initialized in my systemd service UNIT settings.

I've fixed this by added a 30sec delay before having systemd launch homebridge to let the pi _settle-down_ first by adding this to the homebridge.service systemd file.

```
[Service]
ExecStartPre=/bin/sleep 30

```

I've only noted it here incase others ever post help with the error.
